# Generated by Django 4.2.9 on 2024-03-16 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_black', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminBlackSetting',
        ),
    ]
